"""add location

Revision ID: 8ae23a4a47f9
Revises: 12d0f3ac3e2e
Create Date: 2023-09-14 09:35:02.148148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ae23a4a47f9'
down_revision: Union[str, None] = '12d0f3ac3e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('request_timestamp', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('schedule_relationship', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('bearing', sa.Float(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'request_timestamp')
    )
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.create_foreign_key("stoptime_trips", 'trips', ['trip_id'], ['id'])
        batch_op.create_foreign_key("stoptime_stops", 'stops', ['stop_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stop_times', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('locations')
    # ### end Alembic commands ###
