"""initialise database

Revision ID: fb17249dcdd3
Revises: 
Create Date: 2023-09-11 21:28:08.050579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb17249dcdd3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('url', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=20), nullable=False),
    sa.Column('lang', sa.String(length=2), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('schedule_relationship', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('bearing', sa.Float(), nullable=False),
    sa.Column('speed', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('congestion_level', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('vehicle_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agency_id', sa.String(), nullable=False),
    sa.Column('short_name', sa.String(), nullable=False),
    sa.Column('long_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=6), nullable=False),
    sa.Column('text_color', sa.String(length=6), nullable=False),
    sa.Column('exact_times', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shapes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('dist_traveled', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'sequence')
    )
    op.create_table('stop_times',
    sa.Column('trip_id', sa.String(), nullable=False),
    sa.Column('arrival_time', sa.String(), nullable=False),
    sa.Column('departure_time', sa.String(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('stop_headsign', sa.String(), nullable=False),
    sa.Column('pickup_type', sa.Integer(), nullable=False),
    sa.Column('drop_off_type', sa.Integer(), nullable=False),
    sa.Column('shape_dist_traveled', sa.Float(), nullable=False),
    sa.Column('timepoint', sa.Integer(), nullable=False),
    sa.Column('stop_note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('stop_id')
    )
    op.create_table('stops',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('wheelchair_boarding', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('route_id', sa.String(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('headsign', sa.String(), nullable=False),
    sa.Column('direction_id', sa.Integer(), nullable=False),
    sa.Column('wheelchair_accessible', sa.Integer(), nullable=False),
    sa.Column('route_direction', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('route_id', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    op.drop_table('stops')
    op.drop_table('stop_times')
    op.drop_table('shapes')
    op.drop_table('routes')
    op.drop_table('locations')
    op.drop_table('agencies')
    # ### end Alembic commands ###
